### ISSUE TITLE
Is good-labs.github.io the main repo?

### ISSUE THREAD

**Issue by pdurbin** [good-labs/good-labs.github.io#10]
I guess I'd just like some confirmation that "good-labs.github.io" is the main repo, especially since we decided to do away with the "org" repo. If I have an issue to raise about something in general, this "good-labs.github.io" is the place to raise it, right?

For example, I expect the CONTRIBUTING.md file to be in the main repo but based on discussion at https://github.com/good-labs/good-labs.github.io/issues/2 it sounds like CONTRIBUTING.md should be in the https://github.com/good-labs/.github repo? Is that right?

Sorry to ask two questions at once:

- Is this ("good-labs.github.io") the main repo?
- Should CONTRIBUTING.md go in the ".github" repo?

**Comment by vsoch** [comment]
I’d say we should put it in both- it’s expected here, and an propagate the other repos from the global .github repo.

**Comment by vsoch** [comment]
And yes this is now the main “org” repo.

**Comment by pdurbin** [comment]
Ok, thanks. I was asking because I think CONTRIBUTING.md should be in the main repo. See also https://github.com/good-labs/good-labs.github.io/issues/2
