### ISSUE TITLE
web portal vs website

### ISSUE THREAD

**Issue by pdurbin** [good-labs/good-labs.github.io#13]
I keep encountering the phrase "web portal" when I think it should probably say "website". Do we have a preference for either one?

**Comment by vsoch** [comment]
I like web portal, but it’s just personal preference. Website is very 2005 :)

**Comment by pdurbin** [comment]
Huh. I'd say the opposite. Portals were big a decade or so ago. Yahoo had one. I don't know. I know people who really like the term "grid" even though I think it's a bit archaic. Mostly I'm interested in consistency. I'll close this but feel free to re-open if you recant on portal. 😄
