### ISSUE TITLE
Proposal: FUNDING.md

### ISSUE THREAD

**Issue by vsoch** [good-labs/good-labs.github.io#15]
To help with open source transparency, we can provide a FUNDING.md template where an entity can declare conflicts of interest, funding, etc.

**Comment by vsoch** [comment]
It looks like there are projects that already have some form of funding file, check out one from jessfraz:

https://github.com/jessfraz/branch-cleanup-action/blob/master/.github/FUNDING.yml

**Comment by vsoch** [comment]
Derp, I forgot I need to get it enabled for good labs! For now this one can sit and wait, will test when they are activated.

**Comment by pdurbin** [comment]
Huh. Interesting. Is the FUNDING.yml by @jessfraz based on a standard?

**Comment by jessfraz** [comment]
It’s a undocumented feature of github I believe

**Comment by vsoch** [comment]
Wicked! I love finding and learning these little secret goodies :candy: Thanks @jessfraz :)

**Comment by vsoch** [comment]
I just added this, https://good-labs.github.io/docs/projects/funding/ will clean up a bit and then share more widely. Thanks y'all!
