### ISSUE TITLE
data liberation

### ISSUE THREAD

**Issue by pdurbin** [good-labs/good-labs.github.io#17]
In general, I get nervous when I put information into a system and have trouble getting it out.

Is there interest in coming up with solutions to download our data from the following services?

- GitHub issues
- Gitter chat room conversations
- Murmur mailing list archives
- ...

I would suggest that we could have an issue per service. Or if there is no interest in data liberation, we could simply close this issue. 😄

**Comment by vsoch** [comment]
GitHub issues are accessible via API. Murmur is unlikely to be hugely used, and if the list is used we can re-evaluate. Gitter also appears to have an [API](https://developer.gitter.im/docs/welcome) although it's more in development (and they had posted recently for hiring so I expect it to be for a bit). I don't think I'm greatly concerned at this point about any on the list.

**Comment by vsoch** [comment]
You should easily be able to create (if it's not already done) a script to run regularly to download content, if you think this is hugely important.

**Comment by pdurbin** [comment]
@vsoch thanks for the encouragement. I went ahead and started working on data liberation for GitHub issues in #22.

I'll make issues for other services eventually. :smile:

**Comment by vsoch** [comment]
Sounds good! I just got a skeleton working for the human list -> https://good-labs.github.io/human-menu/ It's just enough to load the list and have different local storage settings, have lots more to do but I'm happy to have a start! Here is the JavaScript object (and look in index.js for how it's used so far).

https://github.com/good-labs/human-menu/blob/master/assets/js/human-menu.js

I'll ping you when it's more of a full working thing for feedback.

**Comment by pdurbin** [comment]
Since #22 was closed I guess I'll close this issue as well. For the record, I've had good luck with https://github.com/minrk/archive-gitter though I've never used it in anger. 😄

**Comment by pdurbin** [comment]
I'm reopening this issue because I still want data liberation. I just did a Google search for "community in a box" and I know it's in https://gitter.im/good-labs/community but I can't find it. I'll probably create an issue specific to Gitter and keep this parent issue open until I feel like we have enough data liberation for Good Labs.

**Comment by pdurbin** [comment]
This will be the first order of business for @researchdatamaniacs https://gitter.im/Research-Data-Maniacs/community

@vsoch et. al you are absolutely invited to join us as I mentioned at https://gitter.im/good-labs/community/archives/2020/03/04 !

**Comment by vsoch** [comment]
Is this a new GitHub organization, or just a Gitter channel?

**Comment by vsoch** [comment]
Honestly I'm not super excited about joining an org with "maniacs" in the title, it might not be apparent to you since you are a male, but at least for women just existing and being excited about things we can get a label of hysterical, maniac, crazy, etc.

But for a more important point, I try to limit orgs that I create or join to those that I am fully engaged in. My question here would be why did you make a new GitHub community, why not just use good-labs? I'd like to see good-labs pick up on ideas / projects that we support. Projects focused around data would fall into scope I think.

**Comment by vsoch** [comment]
Anyway, you are definitely free to make another organization if that's the direction that you want! You are always welcome to do work here too. Since this has been labeled a job for this new org, I'm closing the issue here.
