### ISSUE TITLE
add methods of communication to contributing page

### ISSUE THREAD

**Issue by vsoch** [good-labs/good-labs.github.io#2]
e.g., some chat channel, email list, etc.

**Comment by pdurbin** [comment]
Adding https://gitter.im/good-labs/community seems like a good start.

For email, I've been thinking about using Murmur. I met the author at LibrePlanet a few weeks ago. https://murmur.csail.mit.edu is the installation she runs and the paper ( http://people.csail.mit.edu/axz/papers/mailinglists.pdf ) and more are linked from https://murmur.csail.mit.edu/about

**Comment by vsoch** [comment]
oh wicked! Yes I think we should try it out!

**Comment by pdurbin** [comment]
@vsoch you kicked off the new list at https://murmur.csail.mit.edu/thread?group_name=good-labs&tid=1215 but we should create a CONTRIBUTING.md file, right?

**Comment by vsoch** [comment]
Yep, do you want to take a stab? Well chosen templates are good :)

**Comment by vsoch** [comment]
And we should add it to  https://github.com/good-labs/.github

**Comment by pdurbin** [comment]
@vsoch hmm, I guess I could take a stab but I don't know which templates you're talking about. I'm the primary author of https://github.com/IQSS/dataverse/blob/v4.13/CONTRIBUTING.md and I'd be curious if you like it.

Also, I don't really understand the ".github" repo. It gets included somehow? Which repo is the "main" repo? I'd put CONTRIBUTING.md in the main repo.

**Comment by vsoch** [comment]
It’s the same as a .github folder in a repo, but for docs that can be used across the org. Adding a doc in a repo will of course override.

Yes please make your best effort for the contributing doc!

**Comment by pdurbin** [comment]
Ah, so there's an mechanism for overriding. That's good to know. Thanks.

**Comment by pdurbin** [comment]
I got confirmation that this "good-labs.github.io" is the main repo at https://github.com/good-labs/good-labs.github.io/issues/10 so I just opened pull request #11 to add a CONTRIBUTING.md file.

**Comment by pdurbin** [comment]
pull request #11 was merge so I'm closing this.
