### ISSUE TITLE
No proposal in "projects" directory for Doctopus

### ISSUE THREAD

**Issue by pdurbin** [good-labs/good-labs.github.io#20]
Other proposals have something like "Read more about the project here" and Doctopus probably should too.

**Comment by vsoch** [comment]
There isn’t a repo yet, so I haven’t added this. But yes we will eventually have that, and feel free to leave the issue open until then.

**Comment by pdurbin** [comment]
Ok, I guess this proposal is sort of grandfathered into the process we discussed at https://gitter.im/good-labs/community?at=5ccf216cb4700e023d289263

"I think first you would want to write up the project in detail, add to the good-labs.github.io site, and then PR so we can discuss, then another repo"

What's needed at this time are details, a file in "projects", not a repo. That's my understanding. The repo comes after the details are provided in a pull request.

**Comment by vsoch** [comment]
I have a file, just haven't added it yet :) This is grandfathered into "will add when I think it's right."

**Comment by pdurbin** [comment]
In pull request #26 I'm suggesting that Doctopus could be removed from the project list until there's a project proposal. That way we can close this issue. The project proposal process should be documented.
