### ISSUE TITLE
data liberation: GitHub Issues

### ISSUE THREAD

**Issue by pdurbin** [good-labs/good-labs.github.io#22]
I just ran `github-backup` ( https://packages.ubuntu.com/bionic/github-backup ) with no arguments and pushed the "github" branch it created to this repo. This tools gives you more that just GitHub Issues but here is the backup of them: https://github.com/good-labs/good-labs.github.io/tree/github/good-labs_good-labs.github.io/issue

What do we think? Do we like this? Does it add value?

**Comment by vsoch** [comment]
hmm, I don't see how useful it has to have the Github backup on GitHub on the same repo intended to be backed up. Please remove the branch here, and maybe explore a different git server, so if this one goes down, the backup is useful?

**Comment by vsoch** [comment]
So to directly answer your question, it could add value if it's pushed to a version control service that isn't the one it's intended to back up. And there are clear instructions for using, restoring, etc, maybe with a container if possible.

**Comment by vsoch** [comment]
https://github.com/marketplace/backhub

**Comment by vsoch** [comment]
backup  should be:

 - completely automated
 - (mostly) free, or having some free tier
 - to another server

**Comment by vsoch** [comment]
GitHub also has backups, of course https://www.quora.com/Does-GitHub-backup-all-of-its-data

**Comment by pdurbin** [comment]
> I don't see how useful it has to have the Github backup on GitHub on the same repo intended to be backed up.

The idea is that everyone who clones the repo has a complete backup of not only the code/docs/config in the repo itself but also the GitHub issues. The backups are decentralized. See also LOCKSS (Lots of Copies Keep Stuff Safe) at https://en.wikipedia.org/wiki/LOCKSS 😄 

If you don't like the idea, that's totally fine. We can just close this issue. Please go ahead and blow away the "github" branch if you want to. It was just an experiment. 😄 And easy one too. `apt-get install` a package. Run a single command. Push. Quick. Simple.
