### ISSUE TITLE
project proposal: Searchable Linkable Open Public Indexed (SLOPI) Communication

### ISSUE THREAD

**Issue by pdurbin** [good-labs/good-labs.github.io#23]
After talking the idea out a bit at https://gitter.im/good-labs/community?at=5ccf1cbd6a84d76ed84dc3fb I'm submitting the following proposal as project. A pull request is on its way.

# Searchable Linkable Open Public Indexed (SLOPI) Communication

## What is it?

Messages written in the SLOPI (pronounced "sloppy") communication style are:

- Searchable: Messages can be found using Google or other search engines.
- Linkable: Messages have a permalink.
- Open: Messages are in the open.
- Public: Messages are public.
- Indexed: Messages are indexed by search engines.

This phrasing, especially with regard to messages being searchable and linkable, is inspired by the [discussion][] criteria of [Core Infrastructure Initiative (CII) Best Practices][] program.

Examples of communication tools that support the SLOPI style include:

- mailing lists with public archives
- Gitter
- IRC channels with public logs
- XMPP rooms with public logs

While open source projects should endeavor to communicate in the SLOPI style whenever possible, this style is inappropriate for security, code of conduct violations, and telling co-workers on your floor that you brought in donuts.

The SLOPI style can take some getting used to if you are new to open source culture. It's ok to be a little sloppy. Please don't worry if the message you send isn't perfect. The fact that you sent it in the open is appreciated. Open source is getting friendlier. A thick skin isn't as necessary as it was in the past.

[discussion]: https://github.com/coreinfrastructure/best-practices-badge/commit/65ebe74d7bfdf661502978311200d0c32f7b8be8
[Core Infrastructure Initiative (CII) Best Practices]: https://bestpractices.coreinfrastructure.org

## Why do we need it?

Open source projects are adopting Slack, forgetting the importance of public and open communication. How can your users and contributors know what you're thinking if the majority of discussion and decision making is done in Slack? Did you forget that you have a mailing list with public archives? Have you considered chat tools that support a SLOPI communication style?

## Project Plan

- Tell success stories of projects that have adopted a SLOPI communication style as positive role models. Link to the various tooks they use.
- List alternatives to Slack that are SLOPI, such as Gitter, logged IRC channels, and logged XMPP rooms.
- List blog posts that have made the argument that Slack is bad for open source.

## Resources

- [Considering the Use of Walled Gardens for FLOSS Project Communication][] by @megansquire

[Considering the Use of Walled Gardens for FLOSS Project Communication]: https://doi.org/10.1007/978-3-319-57735-7_1

**Comment by vsoch** [comment]
So the takeaway is... "Don't be sloppy, be SLOPI!"

**Comment by pdurbin** [comment]
@vsoch heh. Yes, exactly. Reviews on pull request #24 are very welcome! Or comments here. Whatever. What do you and others think? :smile:

**Comment by pdurbin** [comment]
I'm realizing that I focused on:

- mailing lists
- chat

but I'm thinking that I should include other forms of communication including:

- forums
- issue trackers
- roadmaps
- kanban boards

After all, it's all communication. What else am I forgetting?

I just started a doc where I have the full list and some examples from Jupyter and other communities I'm at least vaguely familiar with: https://docs.google.com/spreadsheets/d/1wvG3XTd5YwA-SliOUCavQgqfK1jLVnlL9tuUsjHR0Ik/edit?usp=sharing

**Comment by pdurbin** [comment]
Ok, in pull request #24 I added forums, issue trackers, roadmaps, and kanban boards in 32212df

**Comment by vsoch** [comment]
This project is a really great idea! I added my review, and we can follow up there.

**Comment by pdurbin** [comment]
@vsoch thanks, I'll comment on your review but at a high level, what do you (and anyone reading this) think about the term "SLOPI" and the pronunciation ("sloppy")?

I'm influenced by the FAIR data principles. You can ask, "Is this data FAIR?" And if someone asks what that means, you say, "Oh, it means that the data meet standards of findability, accessibility, interoperability, and reusability. Here's the Wikipedia page: https://en.wikipedia.org/wiki/FAIR_data "

Likewise, if SLOPI becomes a thing, a term that people start to use, people can start to say things like, "We aren't being SLOPI enough. Let's move this conversation from Slack to Gitter or the mailing list."

In my pull request I tried to give credit to @kfogel (who may or may not remember me from LibrePlanet or from giving feedback on his fantastic book, "Producing Open Source Software: How to Run a Successful Free Software Project" at https://producingoss.com as well as @david-a-wheeler whom I've never met I don't believe but who I think I agree with 100% in terms of transparent communication when I read what he wrote at https://github.com/coreinfrastructure/best-practices-badge/issues/186 and in the pull request I linked from my pull request for this issue. If either of them see this, I think "discussion" should be elevated from "Other" to its own category or whatever. I'm happy to make a pull request for this. Here's how "Other" appears now for the CII Best Practices information for curl at https://bestpractices.coreinfrastructure.org/en/projects/63

![Screenshot from 2019-05-06 17-43-50](https://user-images.githubusercontent.com/21006/57257619-f9e3c480-7027-11e9-8ba5-c35b2d8c03c9.png)

The idea is that you have a term, a concept, to hang your hat on. I came up with SLOPI in a few minutes, but I'm open to other terms for the same concept. I don't care what we call it as long as we're all on the same page. :smile:

**Comment by pdurbin** [comment]
I created a new repo and GitHub Project. I opened pull request https://github.com/good-labs/good-labs.github.io/pull/25 to adjust the project plan to link to them. My plan is to use GitHub issues in the new repo to track ideas and invite others to participate in the project.

**Comment by vsoch** [comment]
@pdurbin I apologize that I didn't see this comment and provide feedback here. For pull requests, you should generally not merge until discussion is finished there - next time please point me to this issue if I had missed discussion.

> @vsoch thanks, I'll comment on your review but at a high level, what do you (and anyone reading this) think about the term "SLOPI" and the pronunciation ("sloppy")?

I really like it! I think it's a nice contradiction and funny. 

> I'm influenced by the FAIR data principles. You can ask, "Is this data FAIR?" And if someone asks what that means, you say, "Oh, it means that the data meet standards of findability, accessibility, interoperability, and reusability. Here's the Wikipedia page: https://en.wikipedia.org/wiki/FAIR_data "

Understood.

> Likewise, if SLOPI becomes a thing, a term that people start to use, people can start to say things like, "We aren't being SLOPI enough. Let's move this conversation from Slack to Gitter or the mailing list."

Yes, this is an example of why it's funny :)

> In my pull request I tried to give credit to @kfogel (who may or may not remember me from LibrePlanet or from giving feedback on his fantastic book, "Producing Open Source Software: How to Run a Successful Free Software Project" at https://producingoss.com as well as @david-a-wheeler whom I've never met I don't believe but who I think I agree with 100% in terms of transparent communication when I read what he wrote at coreinfrastructure/best-practices-badge#186 and in the pull request I linked from my pull request for this issue. If either of them see this, I think "discussion" should be elevated from "Other" to its own category or whatever. 

Definitely in support of including more people! Could you clarify what you mean by "discussion should be elevated from Other?"

> The idea is that you have a term, a concept, to hang your hat on. I came up with SLOPI in a few minutes, but I'm open to other terms for the same concept. I don't care what we call it as long as we're all on the same page.

:)

**Comment by vsoch** [comment]
Project is added, so I'm closing the issue. Feel free to comment if you have further things to discuss.

**Comment by kfogel** [comment]
I love that you've codified this, @durbin.  I worry that the acronym will put some people off -- it's cute that it sounds like "sloppy", but it's also a disadvantage, because people don't like to be sloppy :-) -- but maybe I'm overthinking it and that won't be a problem in practice.

One quality is only included by implication: "Archive" (or "Permanent").  I'm not sure whether there's a way to fit that into the acronym, or to make a new acronym... again, it's implied anyway, so perhaps "SLOPI" is the way to go.

Please consider writing a blog post about this, if you have the time, so that when people introduce the term "SLOPI" into a conversation they have a canonical reference they can point others to.

**Comment by vsoch** [comment]
@kfogel it would be great to get your feedback on the Greater Good Affirmation too -> https://github.com/good-labs/greater-good-affirmation

GitHub Livestream starting in like, 3 minutes! https://live-stream.github.com/ I hope it's not lame, but I've been excited all day :)

**Comment by vsoch** [comment]
Looks like they are streaming ads until 4:30pm EST (still excited).

**Comment by pdurbin** [comment]
@kfogel thanks for the feedback! This issue (#23) was about if Good Labs even wants to take this project. There's a new repo for the SLOPI project itself and I copied your feedback over to https://github.com/good-labs/slopi-communication/issues/3 where I'd love to discuss more!

More feedback from all is welcome! Thank you!
