### ISSUE TITLE
Process for adding members to teams for maintainers

### ISSUE THREAD

**Issue by pdurbin** [good-labs/good-labs.github.io#27]
Yesterday I had lunch with my friend @ysuarez and because I asked him to help me do some research for https://github.com/good-labs/slopi-communication/issues/2 I thought I'd give him credit and visibility by creating a "slopi-read" team at https://github.com/orgs/good-labs/teams/slopi-read/members and co-assigning him to that issue. Creating the team was not a problem but now I'm blocked adding him to the team. The "Invite" button is not clickable for me. Here's a screenshot:

<img width="824" alt="Screen Shot 2019-05-25 at 6 48 51 AM" src="https://user-images.githubusercontent.com/21006/58368351-da6ae980-7eb9-11e9-8b3a-1e9b38019222.png">

Let's document what people who start projects under good-labs need to do to invite people to join GitHub teams associated with their projects. I'm open to suggestions of where to document this. Perhaps a future version of https://good-labs.github.io/contributing/ ?

The audience for this documentation is "maintainers" to use GitHub's terms. Here's a screenshot showing that I'm a maintainer:

<img width="824" alt="Screen Shot 2019-05-25 at 6 59 32 AM" src="https://user-images.githubusercontent.com/21006/58368415-cc699880-7eba-11e9-8940-104fa9b7add1.png">

**Comment by vsoch** [comment]
Maybe an org level .github folder?

**Comment by vsoch** [comment]
:) https://github.com/good-labs/.github

**Comment by pdurbin** [comment]
@vsoch ok, do you like this pull request I just made? https://github.com/good-labs/.github/pull/2

**Comment by vsoch** [comment]
Is @ysuarez active on GitHub, and does he want to be added?

**Comment by pdurbin** [comment]
Well, he's now my second stargazer! https://github.com/good-labs/slopi-communication/stargazers

Why do you ask?

**Comment by vsoch** [comment]
Because I’m fairly certain he can speak for himself :)

**Comment by pdurbin** [comment]
Sure. But I believe he's a late riser and it's a holiday weekend. :smile:

**Comment by ysuarez** [comment]
Good morning. Yes, please add me to this team.

**Comment by vsoch** [comment]
hey @ysuarez, nice to meet you! Glad to do so.

**Comment by ysuarez** [comment]
It is a pleasure to meet you!

**Comment by pdurbin** [comment]
@vsoch thanks for adding @ysuarez as the third member of Good Labs! I just created pull request #29 to close this issue.

@ysuarez you are very welcome to join the conversation at https://gitter.im/good-labs/community :smile:
